apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: "${image_name}"
        imagePullPolicy: "Never"
        ports:
        - containerPort: 8888
        readinessProbe:
          httpGet:
            path: /actuator/info
            port: 8888
          initialDelaySeconds: 20
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8888
          initialDelaySeconds: 60
          timeoutSeconds: 2
        volumeMounts:
        - name: secret-object
          mountPath: "/home/secrets/"
          readOnly: true
      volumes:
        - name: secret-object
          secret:
            secretName: secret-object
